version: "3.8"

services:
  api:
    build: .
    container_name: facial_extraction_api
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    restart: always

  streamlit:
    build: .
    container_name: facial_extraction_ui
    ports:
      - "8501:8501"
    depends_on:
      - api
    command: ["streamlit", "run", "frontend/app_streamlit.py", "--server.port=8501", "--server.address=0.0.0.0"]
